services:
  - type: web
    name: render-test-frontend
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    pullRequestPreviewsEnabled: false

  - type: web
    name: render-test-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
